include:
  - project: 'tmobile/templates'
    file:
      - '/gitlab-ci/.tmo.global.common.gitlab-ci.yml'
      - '/gitlab-ci/.tmo.function.gradleBuild.gitlab-ci.yml'
      - '/gitlab-ci/.tmo.job.mavenBuild.gitlab-ci.yml'

stages:
  - tmo
  - test
  - build
  
test:
  stage: test
  script: echo "testing in progress"